version: '3.8'

services:
  api-gateway:
    image: nginx:alpine
    container_name: smartcart-nginx-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
